In [1]:
#Question1- Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#Answer-
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

# Interchanging rows and columns (Transpose the array)
transposed_arr = np.transpose(arr)

arr, transposed_arr


(array([[37, 71, 36],
        [55, 69, 86],
        [ 3, 19, 76]]),
 array([[37, 55,  3],
        [71, 69, 19],
        [36, 86, 76]]))

In [3]:
#Question2-Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
#Answer-
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("2x5 array:\n", array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("5x2 array:\n", array_5x2)



2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
#Question3-Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
#Answer-
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 array:\n", array_4x4)
print("6x6 array with border of zeros:\n", array_6x6)


4x4 array:
 [[0.6417873  0.19226043 0.21427011 0.34295422]
 [0.14704765 0.93249947 0.02186197 0.7863515 ]
 [0.3263684  0.72711022 0.21682176 0.37492169]
 [0.4309224  0.23752264 0.04494278 0.52904651]]
6x6 array with border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.6417873  0.19226043 0.21427011 0.34295422 0.        ]
 [0.         0.14704765 0.93249947 0.02186197 0.7863515  0.        ]
 [0.         0.3263684  0.72711022 0.21682176 0.37492169 0.        ]
 [0.         0.4309224  0.23752264 0.04494278 0.52904651 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [5]:
#Question4-Using NumPy, create an array of integers from 10 to 60 with a step of 5.
#Answer-
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)

print("Array:", array)

Array: [10 15 20 25 30 35 40 45 50 55 60]


In [6]:
#Question5-Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.
#Answer-
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

print("Original array:", array)
print("Uppercase array:", uppercase_array)
print("Lowercase array:", lowercase_array)
print("Titlecase array:", titlecase_array)
print("Capitalized array:", capitalize_array)

Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Titlecase array: ['Python' 'Numpy' 'Pandas']
Capitalized array: ['Python' 'Numpy' 'Pandas']


In [7]:
#Question6-Generate a NumPy array of words. Insert a space between each character of every word in the array
#Answer-
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("Original array:", words_array)
print("Array with spaces between characters:", spaced_words_array)

Original array: ['python' 'numpy' 'pandas']
Array with spaces between characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


In [8]:
#Question7-Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
#Answer-
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = np.add(array1, array2)

# Perform element-wise subtraction
subtraction = np.subtract(array1, array2)

# Perform element-wise multiplication
multiplication = np.multiply(array1, array2)

# Perform element-wise division
division = np.divide(array1, array2)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Element-wise addition:\n", addition)
print("Element-wise subtraction:\n", subtraction)
print("Element-wise multiplication:\n", multiplication)
print("Element-wise division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [12]:
#Question8-Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
#Answer-
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [11]:
#Question9- Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
#Answer-
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Vectorized version of the prime-checking function
vectorized_is_prime = np.vectorize(is_prime)

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Apply the vectorized prime-checking function to the array
prime_mask = vectorized_is_prime(random_integers)

# Extract the prime numbers using the boolean mask
prime_numbers = random_integers[prime_mask]

print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)

Random Integers:
 [ 84 872 464 861 279 662 701  40 148 726 738 803 624  17  42 882 149 237
 180  49  99  18 350 444 492 704 129 724 594 359 367 235 965 796 526 410
 409 267 530 604  21 320 284 402 595 457 779 528 917 763  95 946 762  72
 481 867 562 944 331 109 224 178 747 947 673 943 350 350 424 791 124 249
 996 430 654 944 806 727 191 643 854 436 946 422 958 707 222 696 981 354
 869 602   5 200 375 569 939  54 482 297]
Prime Numbers:
 [701  17 149 359 367 409 457 331 109 947 673 727 191 643   5 569]


In [14]:
#Question10- Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
#answer-
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
# For example, let's generate temperatures between 0 and 35 degrees Celsius
daily_temperatures = np.random.uniform(0, 35, size=30)

# Reshape the array into weeks (assuming each week has 7 days)
# Calculate the number of weeks needed
days_per_week = 7
num_weeks = len(daily_temperatures) // days_per_week

# Reshape the array into the shape (num_weeks, days_per_week)
weekly_temperatures = daily_temperatures[:num_weeks * days_per_week].reshape(num_weeks, days_per_week)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:\n", daily_temperatures)
print("Weekly Temperatures:\n", weekly_temperatures)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures:
 [28.50862529  7.767014   17.64925958 19.42368916 22.53309444  8.99292606
 19.81521432  1.9221044   8.08902235 31.94676199 19.90471145 24.59982289
  6.78407747  9.76900461  4.22411229 13.84292371 30.50261217 28.56036717
 26.26208241 31.46147391 10.87492794  2.42590908 25.03296565 33.5669158
 32.54613464  2.06101589 32.27390108 22.74389289 19.08167716  9.45618032]
Weekly Temperatures:
 [[28.50862529  7.767014   17.64925958 19.42368916 22.53309444  8.99292606
  19.81521432]
 [ 1.9221044   8.08902235 31.94676199 19.90471145 24.59982289  6.78407747
   9.76900461]
 [ 4.22411229 13.84292371 30.50261217 28.56036717 26.26208241 31.46147391
  10.87492794]
 [ 2.42590908 25.03296565 33.5669158  32.54613464  2.06101589 32.27390108
  22.74389289]]
Weekly Averages:
 [17.81283184 14.71650074 20.81835709 21.52153357]
